---
abstract: 'Manage and minify .css and .js assets in a Dancer application'
author:
  - 'Michael Vu <email@michael.vu>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300034, CPAN::Meta::Converter version 2.120921'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dancer-Plugin-Assets
requires:
  Dancer: 0
  Dancer::Plugin: 0
  File::Assets: 0
  Test::TCP: 0
  URI: 0
version: 1.1
